import type { AssessmentCategory } from '../../types.ts';

export const categories: AssessmentCategory[] = [
  { id: 'cybersecurity', name: 'Cybersecurity', shortDescription: 'Protection against common security threats and business disruption.', businessExplanation: 'Cybersecurity health reflects how well the business protects sensitive data, accounts, devices, and systems from preventable compromise.', weight: 18, standards: [], order: 1 },
  { id: 'business-continuity', name: 'Business Continuity and Disaster Recovery', shortDescription: 'Ability to keep operating through outages, data loss, and vendor failures.', businessExplanation: 'Continuity planning determines whether the business can recover critical systems quickly enough to avoid unacceptable revenue, service, or reputation damage.', weight: 15, standards: [], order: 2 },
  { id: 'identity-access', name: 'Identity and Access Management', shortDescription: 'Controls for who can access business systems and administrative tools.', businessExplanation: 'Access management reduces the chance that a lost password, former employee account, or shared administrator login becomes a business incident.', weight: 12, standards: [], order: 3 },
  { id: 'technology-operations', name: 'Technology Operations', shortDescription: 'Day-to-day reliability, ownership, documentation, monitoring, and support.', businessExplanation: 'Operations health shows whether technology issues are handled predictably or depend on heroics and undocumented knowledge.', weight: 12, standards: [], order: 4 },
  { id: 'productivity-collaboration', name: 'Productivity and Collaboration', shortDescription: 'How effectively teams use communication, document, and workflow tools.', businessExplanation: 'Collaboration health indicates whether tools make work faster and clearer or create duplicated effort and information silos.', weight: 10, standards: [], order: 5 },
  { id: 'cloud-infrastructure', name: 'Cloud and Infrastructure', shortDescription: 'Reliability, maintainability, and security of hosting and core infrastructure.', businessExplanation: 'Infrastructure health reflects whether the systems running the business are understandable, supportable, secure, and resilient.', weight: 10, standards: [], order: 6 },
  { id: 'governance-risk', name: 'Governance and Risk Management', shortDescription: 'Decision ownership, policies, vendor accountability, and risk visibility.', businessExplanation: 'Governance health shows whether leaders can see technology risk clearly and make informed investment decisions.', weight: 8, standards: [], order: 7 },
  { id: 'ai-readiness', name: 'AI Readiness', shortDescription: 'Preparedness to use AI tools safely, productively, and responsibly.', businessExplanation: 'AI readiness measures whether the business can capture productivity gains without exposing sensitive data or creating unmanaged risk.', weight: 7, standards: [], order: 8 },
  { id: 'cost-optimization', name: 'Cost Optimization', shortDescription: 'Visibility and control over software, cloud, and vendor spend.', businessExplanation: 'Cost health indicates whether technology spending is intentional, reviewed, and tied to business value.', weight: 5, standards: [], order: 9 },
  { id: 'vendor-strategy', name: 'Vendor and Technology Strategy', shortDescription: 'Fit, ownership, and lifecycle planning for key vendors and platforms.', businessExplanation: 'Technology strategy health shows whether vendor decisions support the business or create avoidable lock-in, fragility, or duplicated tools.', weight: 3, standards: [], order: 10 },
];
