import type { CapabilityQuestion } from '../../types.ts';

export const criticalDataInventoryQuestions: CapabilityQuestion[] = [
  {
    id: 'critical-data-coverage',
    capabilityId: 'critical-data-inventory',
    prompt: 'Is there a current inventory of the data the business must protect or recover?',
    description: 'Consider customer, financial, operational, employee, legal, intellectual property, and safety-related information.',
    responseType: 'single-choice',
    evidenceRequirements: [{ id: 'critical-data-register', label: 'Critical-data register', description: 'A current record of important data sets, their business purpose, and where they are stored or processed.', preferredSource: 'documentation' }],
    options: [
      { id: 'unknown', label: 'Not known', maturityScore: 1 },
      { id: 'informal', label: 'Known informally by business or technical staff', maturityScore: 2 },
      { id: 'partial', label: 'Inventory covers the most important data', maturityScore: 3 },
      { id: 'reviewed', label: 'Inventory is documented and reviewed with business owners', maturityScore: 4 },
      { id: 'managed', label: 'Inventory is connected to protection, recovery, and change processes', maturityScore: 5 },
    ],
    allowUnknown: true,
    unknownBehavior: { type: 'visibility-finding', findingId: 'critical-data-visibility-gap' },
    importance: 5,
    severity: 'high',
    foundational: true,
    standardMappingIds: ['critical-data-cis', 'critical-data-nist'],
  },
  {
    id: 'critical-data-ownership',
    capabilityId: 'critical-data-inventory',
    prompt: 'Do critical data sets have accountable business owners?',
    responseType: 'single-choice',
    evidenceRequirements: [{ id: 'critical-data-ownership-record', label: 'Data ownership record', description: 'A record showing business owners for important data sets and decisions they are accountable for.', preferredSource: 'documentation' }],
    options: [
      { id: 'unknown', label: 'Not known', maturityScore: 1 },
      { id: 'informal', label: 'Ownership depends on individual knowledge', maturityScore: 2 },
      { id: 'partial', label: 'Owners are recorded for some critical data', maturityScore: 3 },
      { id: 'reviewed', label: 'Owners are recorded and reviewed', maturityScore: 4 },
      { id: 'managed', label: 'Ownership drives access, retention, protection, and recovery decisions', maturityScore: 5 },
    ],
    allowUnknown: true,
    unknownBehavior: { type: 'visibility-finding', findingId: 'critical-data-ownership-gap' },
    importance: 4,
    severity: 'high',
    foundational: true,
    standardMappingIds: ['critical-data-cis', 'critical-data-iso27001'],
  },
  {
    id: 'critical-data-review',
    capabilityId: 'critical-data-inventory',
    prompt: 'Is the critical-data inventory reviewed for new locations, duplicate copies, and changing business needs?',
    responseType: 'single-choice',
    evidenceRequirements: [{ id: 'critical-data-review', label: 'Data inventory review', description: 'A recent review showing new storage locations, duplicate copies, ownership changes, or unresolved data risks.', preferredSource: 'manual-review' }],
    options: [
      { id: 'unknown', label: 'Not reviewed or not known', maturityScore: 1 },
      { id: 'informal', label: 'Issues are handled when noticed', maturityScore: 2 },
      { id: 'partial', label: 'Reviews happen for some data areas', maturityScore: 3 },
      { id: 'reviewed', label: 'Reviews occur on a defined schedule', maturityScore: 4 },
      { id: 'managed', label: 'Review results drive protection, retention, and modernization decisions', maturityScore: 5 },
    ],
    allowUnknown: true,
    unknownBehavior: { type: 'visibility-finding', findingId: 'critical-data-review-gap' },
    importance: 4,
    severity: 'moderate',
    foundational: true,
    standardMappingIds: ['critical-data-cis', 'critical-data-nist'],
  },
];
