import type { CapabilityQuestion } from '../../types.ts';

export const identityInventoryQuestions: CapabilityQuestion[] = [
  {
    id: 'identity-inventory-coverage',
    capabilityId: 'identity-inventory',
    prompt: 'Is there a current inventory of the identities that can access important business systems?',
    description: 'Consider employees, contractors, administrators, service accounts, guests, external users, and major identity providers.',
    responseType: 'single-choice',
    evidenceRequirements: [{ id: 'identity-inventory', label: 'Identity inventory', description: 'A current report or record covering relevant human, administrative, service, and external identities.', preferredSource: 'documentation' }],
    options: [
      { id: 'informal', label: 'Known informally or across disconnected systems', maturityScore: 2 },
      { id: 'partial', label: 'Inventory covers the main workforce and systems', maturityScore: 3 },
      { id: 'reviewed', label: 'Inventory is centralized and reviewed', maturityScore: 4 },
      { id: 'managed', label: 'Inventory is routinely reconciled with identity providers and systems', maturityScore: 5 },
    ],
    allowUnknown: true,
    unknownBehavior: { type: 'visibility-finding', findingId: 'identity-inventory-visibility-gap' },
    importance: 5,
    severity: 'high',
    foundational: true,
    standardMappingIds: ['identity-inventory-cis', 'identity-inventory-nist'],
  },
  {
    id: 'identity-inventory-ownership',
    capabilityId: 'identity-inventory',
    prompt: 'Do important identities and identity systems have accountable owners?',
    responseType: 'single-choice',
    evidenceRequirements: [{ id: 'identity-ownership-record', label: 'Identity ownership record', description: 'A record showing who owns identity providers, administrative accounts, service accounts, and access decisions.', preferredSource: 'documentation' }],
    options: [
      { id: 'informal', label: 'Ownership depends on individual knowledge', maturityScore: 2 },
      { id: 'partial', label: 'Owners are recorded for the most important identities and systems', maturityScore: 3 },
      { id: 'reviewed', label: 'Owners are recorded and reviewed', maturityScore: 4 },
      { id: 'managed', label: 'Ownership is part of identity and access processes', maturityScore: 5 },
    ],
    allowUnknown: true,
    unknownBehavior: { type: 'visibility-finding', findingId: 'identity-inventory-ownership-gap' },
    importance: 4,
    severity: 'high',
    foundational: true,
    standardMappingIds: ['identity-inventory-cis', 'identity-inventory-entra'],
  },
  {
    id: 'identity-inventory-review',
    capabilityId: 'identity-inventory',
    prompt: 'Is the identity inventory reviewed for dormant, orphaned, duplicate, or unexpected identities?',
    responseType: 'single-choice',
    evidenceRequirements: [{ id: 'identity-inventory-review', label: 'Identity review record', description: 'A recent review showing dormant, orphaned, duplicate, or unexpected identities and resulting actions.', preferredSource: 'manual-review' }],
    options: [
      { id: 'informal', label: 'Issues are handled when noticed', maturityScore: 2 },
      { id: 'partial', label: 'Reviews happen for some systems or account types', maturityScore: 3 },
      { id: 'reviewed', label: 'Reviews occur on a defined schedule', maturityScore: 4 },
      { id: 'managed', label: 'Review results drive timely remediation and access decisions', maturityScore: 5 },
    ],
    allowUnknown: true,
    unknownBehavior: { type: 'visibility-finding', findingId: 'identity-inventory-review-gap' },
    importance: 4,
    severity: 'high',
    foundational: true,
    standardMappingIds: ['identity-inventory-cis', 'identity-inventory-nist'],
  },
];
