import type { CapabilityQuestion } from '../../types.ts';

export const technologyAssetInventoryQuestions: CapabilityQuestion[] = [
  {
    id: 'technology-asset-coverage',
    capabilityId: 'technology-asset-inventory',
    prompt: 'Is there a current inventory of the technology the business depends on?',
    description: 'Consider endpoints, servers, cloud services, business applications, network equipment, and major vendor platforms.',
    responseType: 'single-choice',
    evidenceRequirements: [{ id: 'technology-inventory', label: 'Technology inventory', description: 'A current list of major technology assets and services in business scope.', preferredSource: 'documentation' }],
    options: [
      { id: 'informal', label: 'Known informally or across disconnected lists', maturityScore: 2 },
      { id: 'partial', label: 'Inventory covers the most important technology', maturityScore: 3 },
      { id: 'reviewed', label: 'Inventory is centralized and reviewed', maturityScore: 4 },
      { id: 'managed', label: 'Inventory is automated or routinely reconciled with the environment', maturityScore: 5 },
    ],
    allowUnknown: true,
    unknownBehavior: { type: 'visibility-finding', findingId: 'technology-asset-visibility-gap' },
    importance: 5,
    severity: 'high',
    foundational: true,
    standardMappingIds: ['technology-inventory-cis', 'technology-inventory-nist'],
  },
  {
    id: 'technology-asset-ownership',
    capabilityId: 'technology-asset-inventory',
    prompt: 'Do important technology assets and services have accountable owners?',
    responseType: 'single-choice',
    evidenceRequirements: [{ id: 'technology-ownership-record', label: 'Technology ownership record', description: 'Inventory fields or a responsibility record showing business and operational owners for important assets.', preferredSource: 'documentation' }],
    options: [
      { id: 'informal', label: 'Ownership depends on individual knowledge', maturityScore: 2 },
      { id: 'partial', label: 'Owners are recorded for some important assets', maturityScore: 3 },
      { id: 'reviewed', label: 'Owners are recorded and reviewed for important assets', maturityScore: 4 },
      { id: 'managed', label: 'Ownership is part of asset lifecycle and change processes', maturityScore: 5 },
    ],
    allowUnknown: true,
    unknownBehavior: { type: 'visibility-finding', findingId: 'technology-asset-ownership-gap' },
    importance: 4,
    severity: 'high',
    foundational: true,
    standardMappingIds: ['technology-inventory-cis', 'technology-inventory-itil'],
  },
  {
    id: 'technology-asset-review',
    capabilityId: 'technology-asset-inventory',
    prompt: 'Is the technology inventory reviewed for unsupported, duplicate, or unmanaged assets?',
    responseType: 'single-choice',
    evidenceRequirements: [{ id: 'technology-inventory-review', label: 'Inventory review record', description: 'A recent review showing stale, unsupported, duplicate, or unmanaged technology and planned actions.', preferredSource: 'documentation' }],
    options: [
      { id: 'informal', label: 'Issues are handled when they become visible', maturityScore: 2 },
      { id: 'partial', label: 'Reviews happen for some technology areas', maturityScore: 3 },
      { id: 'reviewed', label: 'Inventory is reviewed on a defined schedule', maturityScore: 4 },
      { id: 'managed', label: 'Review results drive lifecycle, risk, and investment decisions', maturityScore: 5 },
    ],
    allowUnknown: true,
    unknownBehavior: { type: 'visibility-finding', findingId: 'technology-asset-review-gap' },
    importance: 4,
    severity: 'moderate',
    foundational: true,
    standardMappingIds: ['technology-inventory-cis', 'technology-inventory-nist'],
  },
];
