import type { CapabilityCatalogEntry, CapabilityReadinessStatus, CategoryId, DomainId, ScoringModel } from '../types.ts';

const foundationalCapabilityIds = new Set([
  'business-service-criticality',
  'business-process-mapping',
  'technology-asset-inventory',
  'identity-inventory',
  'critical-data-inventory',
  'service-inventory',
  'infrastructure-inventory',
  'application-inventory',
  'vendor-inventory',
  'technology-ownership',
  'data-ownership',
  'operational-ownership',
  'recovery-requirements',
  'technology-documentation',
]);

const implementedCapabilityIds = new Set(['recovery-capability', 'identity-lifecycle', 'privileged-access']);

function capability(id: string, name: string, domainId: DomainId, primaryCategoryId: CategoryId, scoringModel: ScoringModel, secondaryCategoryIds: CategoryId[] = []): CapabilityCatalogEntry {
  const implementationStatus = implementedCapabilityIds.has(id) ? 'implemented' : 'cataloged';
  const readinessStatus: CapabilityReadinessStatus = implementationStatus === 'implemented' ? 'pilot' : 'structured';

  return {
    id,
    name,
    description: `${name} capability within ${domainId}.`,
    businessOutcome: `${name} is understood, owned, and managed in a way that supports business health and risk decisions.`,
    domainId,
    primaryCategoryId,
    secondaryCategoryIds,
    foundational: foundationalCapabilityIds.has(id),
    scoringModel,
    implementationStatus,
    readiness: {
      status: readinessStatus,
      owner: null,
      reviewer: null,
      lastReviewedAt: null,
      notes: readinessStatus === 'pilot' ? 'Implemented capability module; production methodology review remains required.' : 'Taxonomy entry exists; capability module and methodology content are not complete.',
    },
  };
}

export const capabilityCatalog: CapabilityCatalogEntry[] = [
  capability('business-service-criticality', 'Business Service Criticality', 'business-alignment', 'governance-risk', 'business-capability', ['business-continuity', 'technology-operations']),
  capability('business-process-mapping', 'Business Process Mapping', 'business-alignment', 'governance-risk', 'business-capability', ['technology-operations']),
  capability('technology-ownership', 'Technology Ownership', 'business-alignment', 'governance-risk', 'process-maturity', ['technology-operations']),
  capability('technology-roadmap', 'Technology Roadmap', 'business-alignment', 'vendor-strategy', 'process-maturity', ['cost-optimization']),
  capability('technology-investment-planning', 'Technology Investment Planning', 'business-alignment', 'cost-optimization', 'process-maturity', ['vendor-strategy']),

  capability('identity-inventory', 'Identity Inventory', 'identity-access-management', 'identity-access', 'process-maturity', ['cybersecurity']),
  capability('identity-lifecycle', 'Identity Lifecycle Management', 'identity-access-management', 'identity-access', 'process-maturity', ['cybersecurity', 'governance-risk']),
  capability('authentication', 'Authentication', 'identity-access-management', 'identity-access', 'control-status', ['cybersecurity']),
  capability('authorization-access-control', 'Authorization and Access Control', 'identity-access-management', 'identity-access', 'control-status', ['cybersecurity']),
  capability('privileged-access', 'Privileged Access Management', 'identity-access-management', 'identity-access', 'control-status', ['cybersecurity', 'governance-risk', 'business-continuity']),
  capability('third-party-access', 'Third-Party Access', 'identity-access-management', 'identity-access', 'process-maturity', ['vendor-strategy']),
  capability('service-account-management', 'Service Account Management', 'identity-access-management', 'identity-access', 'control-status', ['cloud-infrastructure']),
  capability('access-review', 'Access Review', 'identity-access-management', 'identity-access', 'process-maturity', ['governance-risk']),

  capability('technology-asset-inventory', 'Technology Asset Inventory', 'device-endpoint-management', 'technology-operations', 'process-maturity', ['cybersecurity']),
  capability('endpoint-lifecycle-management', 'Endpoint Lifecycle Management', 'device-endpoint-management', 'technology-operations', 'process-maturity'),
  capability('endpoint-configuration-management', 'Endpoint Configuration Management', 'device-endpoint-management', 'cybersecurity', 'control-status', ['technology-operations']),
  capability('endpoint-protection', 'Endpoint Protection', 'device-endpoint-management', 'cybersecurity', 'control-status'),
  capability('patch-management', 'Patch Management', 'device-endpoint-management', 'cybersecurity', 'process-maturity', ['technology-operations']),
  capability('mobile-device-management', 'Mobile Device Management', 'device-endpoint-management', 'cybersecurity', 'control-status'),
  capability('unsupported-technology-management', 'Unsupported Technology Management', 'device-endpoint-management', 'cybersecurity', 'process-maturity', ['cloud-infrastructure']),
  capability('device-encryption', 'Device Encryption', 'device-endpoint-management', 'cybersecurity', 'control-status'),

  capability('critical-data-inventory', 'Critical Data Inventory', 'data-protection-information-management', 'governance-risk', 'process-maturity', ['cybersecurity']),
  capability('data-classification', 'Data Classification', 'data-protection-information-management', 'governance-risk', 'process-maturity'),
  capability('data-ownership', 'Data Ownership', 'data-protection-information-management', 'governance-risk', 'process-maturity'),
  capability('data-access-control', 'Data Access Control', 'data-protection-information-management', 'cybersecurity', 'control-status', ['identity-access']),
  capability('encryption', 'Encryption', 'data-protection-information-management', 'cybersecurity', 'control-status'),
  capability('data-retention', 'Data Retention', 'data-protection-information-management', 'governance-risk', 'process-maturity'),
  capability('secure-data-disposal', 'Secure Data Disposal', 'data-protection-information-management', 'governance-risk', 'process-maturity'),
  capability('data-loss-prevention', 'Data Loss Prevention', 'data-protection-information-management', 'cybersecurity', 'control-status', ['productivity-collaboration']),
  capability('backup-coverage', 'Backup Coverage', 'data-protection-information-management', 'business-continuity', 'control-status'),
  capability('backup-protection', 'Backup Protection', 'data-protection-information-management', 'business-continuity', 'control-status', ['cybersecurity']),
  capability('backup-verification', 'Backup Verification', 'data-protection-information-management', 'business-continuity', 'process-maturity'),
  capability('recovery-capability', 'Recovery Capability', 'data-protection-information-management', 'business-continuity', 'business-capability'),

  capability('infrastructure-inventory', 'Infrastructure Inventory', 'infrastructure-platform-management', 'cloud-infrastructure', 'process-maturity', ['technology-operations']),
  capability('cloud-account-governance', 'Cloud Account Governance', 'infrastructure-platform-management', 'cloud-infrastructure', 'process-maturity', ['governance-risk']),
  capability('network-management', 'Network Management', 'infrastructure-platform-management', 'cloud-infrastructure', 'process-maturity'),
  capability('network-segmentation', 'Network Segmentation', 'infrastructure-platform-management', 'cybersecurity', 'control-status', ['cloud-infrastructure']),
  capability('internet-exposure-management', 'Internet Exposure Management', 'infrastructure-platform-management', 'cybersecurity', 'control-status', ['cloud-infrastructure']),
  capability('dns-domain-management', 'DNS and Domain Management', 'infrastructure-platform-management', 'cloud-infrastructure', 'process-maturity'),
  capability('certificate-management', 'Certificate Management', 'infrastructure-platform-management', 'cloud-infrastructure', 'process-maturity'),
  capability('configuration-management', 'Configuration Management', 'infrastructure-platform-management', 'cloud-infrastructure', 'process-maturity'),
  capability('infrastructure-lifecycle-management', 'Infrastructure Lifecycle Management', 'infrastructure-platform-management', 'cloud-infrastructure', 'process-maturity'),
  capability('capacity-performance-management', 'Capacity and Performance Management', 'infrastructure-platform-management', 'cloud-infrastructure', 'process-maturity'),
  capability('infrastructure-resilience', 'Infrastructure Resilience', 'infrastructure-platform-management', 'cloud-infrastructure', 'business-capability', ['business-continuity']),

  capability('security-risk-assessment', 'Security Risk Assessment', 'security-operations', 'cybersecurity', 'process-maturity', ['governance-risk']),
  capability('vulnerability-management', 'Vulnerability Management', 'security-operations', 'cybersecurity', 'process-maturity'),
  capability('security-monitoring', 'Security Monitoring', 'security-operations', 'cybersecurity', 'process-maturity'),
  capability('threat-detection', 'Threat Detection', 'security-operations', 'cybersecurity', 'business-capability'),
  capability('security-incident-response', 'Security Incident Response', 'security-operations', 'cybersecurity', 'process-maturity', ['business-continuity']),
  capability('security-incident-readiness', 'Security Incident Readiness', 'security-operations', 'cybersecurity', 'process-maturity'),
  capability('security-awareness', 'Security Awareness', 'security-operations', 'cybersecurity', 'process-maturity'),
  capability('phishing-email-protection', 'Phishing and Email Protection', 'security-operations', 'cybersecurity', 'control-status'),
  capability('security-testing', 'Security Testing', 'security-operations', 'cybersecurity', 'process-maturity'),
  capability('security-improvement-management', 'Security Improvement Management', 'security-operations', 'cybersecurity', 'process-maturity'),

  capability('service-inventory', 'Service Inventory', 'technology-operations-service-management', 'technology-operations', 'process-maturity'),
  capability('operational-ownership', 'Operational Ownership', 'technology-operations-service-management', 'technology-operations', 'process-maturity'),
  capability('monitoring-alerting', 'Monitoring and Alerting', 'technology-operations-service-management', 'technology-operations', 'process-maturity'),
  capability('incident-management', 'Incident Management', 'technology-operations-service-management', 'technology-operations', 'process-maturity'),
  capability('problem-management', 'Problem Management', 'technology-operations-service-management', 'technology-operations', 'process-maturity'),
  capability('change-management', 'Change Management', 'technology-operations-service-management', 'technology-operations', 'process-maturity'),
  capability('release-deployment-management', 'Release and Deployment Management', 'technology-operations-service-management', 'technology-operations', 'process-maturity'),
  capability('technology-documentation', 'Technology Documentation', 'technology-operations-service-management', 'technology-operations', 'process-maturity'),
  capability('support-management', 'Support Management', 'technology-operations-service-management', 'technology-operations', 'process-maturity'),
  capability('escalation-management', 'Escalation Management', 'technology-operations-service-management', 'technology-operations', 'process-maturity'),
  capability('maintenance-management', 'Maintenance Management', 'technology-operations-service-management', 'technology-operations', 'process-maturity'),
  capability('service-performance-management', 'Service Performance Management', 'technology-operations-service-management', 'technology-operations', 'process-maturity'),

  capability('business-impact-analysis', 'Business Impact Analysis', 'business-continuity-resilience', 'business-continuity', 'process-maturity'),
  capability('recovery-requirements', 'Recovery Requirements', 'business-continuity-resilience', 'business-continuity', 'business-capability'),
  capability('business-continuity-planning', 'Business Continuity Planning', 'business-continuity-resilience', 'business-continuity', 'process-maturity'),
  capability('disaster-recovery-planning', 'Disaster Recovery Planning', 'business-continuity-resilience', 'business-continuity', 'process-maturity'),
  capability('recovery-ownership', 'Recovery Ownership', 'business-continuity-resilience', 'business-continuity', 'process-maturity'),
  capability('recovery-documentation', 'Recovery Documentation', 'business-continuity-resilience', 'business-continuity', 'process-maturity'),
  capability('recovery-testing', 'Recovery Testing', 'business-continuity-resilience', 'business-continuity', 'process-maturity'),
  capability('crisis-communication', 'Crisis Communication', 'business-continuity-resilience', 'business-continuity', 'process-maturity'),
  capability('vendor-continuity', 'Vendor Continuity', 'business-continuity-resilience', 'business-continuity', 'process-maturity', ['vendor-strategy']),
  capability('alternative-work-arrangements', 'Alternative Work Arrangements', 'business-continuity-resilience', 'business-continuity', 'business-capability'),
  capability('key-person-dependency', 'Key Person Dependency', 'business-continuity-resilience', 'business-continuity', 'business-capability', ['governance-risk']),
  capability('resilience-improvement', 'Resilience Improvement', 'business-continuity-resilience', 'business-continuity', 'process-maturity'),

  capability('collaboration-platform-management', 'Collaboration Platform Management', 'productivity-collaboration-knowledge', 'productivity-collaboration', 'process-maturity'),
  capability('document-management', 'Document Management', 'productivity-collaboration-knowledge', 'productivity-collaboration', 'process-maturity'),
  capability('knowledge-management', 'Knowledge Management', 'productivity-collaboration-knowledge', 'productivity-collaboration', 'process-maturity'),
  capability('information-findability', 'Information Findability', 'productivity-collaboration-knowledge', 'productivity-collaboration', 'business-capability'),
  capability('external-sharing-management', 'External Sharing Management', 'productivity-collaboration-knowledge', 'productivity-collaboration', 'control-status', ['cybersecurity']),
  capability('employee-technology-onboarding', 'Employee Technology Onboarding', 'productivity-collaboration-knowledge', 'productivity-collaboration', 'process-maturity'),
  capability('employee-technology-offboarding', 'Employee Technology Offboarding', 'productivity-collaboration-knowledge', 'productivity-collaboration', 'process-maturity', ['identity-access']),
  capability('workflow-management', 'Workflow Management', 'productivity-collaboration-knowledge', 'productivity-collaboration', 'process-maturity'),
  capability('workflow-automation', 'Workflow Automation', 'productivity-collaboration-knowledge', 'productivity-collaboration', 'business-capability'),
  capability('tool-adoption-enablement', 'Tool Adoption and Enablement', 'productivity-collaboration-knowledge', 'productivity-collaboration', 'process-maturity'),
  capability('collaboration-effectiveness', 'Collaboration Effectiveness', 'productivity-collaboration-knowledge', 'productivity-collaboration', 'business-capability'),

  capability('technology-governance', 'Technology Governance', 'governance-risk-compliance', 'governance-risk', 'process-maturity'),
  capability('technology-risk-management', 'Technology Risk Management', 'governance-risk-compliance', 'governance-risk', 'process-maturity'),
  capability('policy-management', 'Policy Management', 'governance-risk-compliance', 'governance-risk', 'process-maturity'),
  capability('regulatory-contractual-requirements', 'Regulatory and Contractual Requirements', 'governance-risk-compliance', 'governance-risk', 'process-maturity'),
  capability('compliance-management', 'Compliance Management', 'governance-risk-compliance', 'governance-risk', 'process-maturity'),
  capability('exception-management', 'Exception Management', 'governance-risk-compliance', 'governance-risk', 'process-maturity'),
  capability('technology-decision-management', 'Technology Decision Management', 'governance-risk-compliance', 'governance-risk', 'process-maturity'),
  capability('assurance-evidence-management', 'Assurance and Evidence Management', 'governance-risk-compliance', 'governance-risk', 'process-maturity'),
  capability('cyber-insurance-readiness', 'Cyber Insurance Readiness', 'governance-risk-compliance', 'governance-risk', 'business-capability', ['cybersecurity']),
  capability('leadership-reporting', 'Leadership Reporting', 'governance-risk-compliance', 'governance-risk', 'process-maturity'),

  capability('vendor-inventory', 'Vendor Inventory', 'vendor-third-party-management', 'vendor-strategy', 'process-maturity'),
  capability('vendor-criticality', 'Vendor Criticality', 'vendor-third-party-management', 'vendor-strategy', 'business-capability'),
  capability('vendor-selection', 'Vendor Selection', 'vendor-third-party-management', 'vendor-strategy', 'process-maturity'),
  capability('vendor-due-diligence', 'Vendor Due Diligence', 'vendor-third-party-management', 'vendor-strategy', 'process-maturity', ['governance-risk']),
  capability('contract-renewal-management', 'Contract and Renewal Management', 'vendor-third-party-management', 'vendor-strategy', 'process-maturity', ['cost-optimization']),
  capability('vendor-access-management', 'Vendor Access Management', 'vendor-third-party-management', 'vendor-strategy', 'process-maturity', ['identity-access']),
  capability('vendor-performance-management', 'Vendor Performance Management', 'vendor-third-party-management', 'vendor-strategy', 'process-maturity'),
  capability('vendor-risk-monitoring', 'Vendor Risk Monitoring', 'vendor-third-party-management', 'vendor-strategy', 'process-maturity'),
  capability('vendor-exit-planning', 'Vendor Exit Planning', 'vendor-third-party-management', 'vendor-strategy', 'process-maturity'),
  capability('concentration-lock-in-risk', 'Concentration and Lock-In Risk', 'vendor-third-party-management', 'vendor-strategy', 'business-capability'),

  capability('technology-budget-visibility', 'Technology Budget Visibility', 'technology-financial-management', 'cost-optimization', 'process-maturity'),
  capability('saas-subscription-management', 'SaaS Subscription Management', 'technology-financial-management', 'cost-optimization', 'process-maturity'),
  capability('license-optimization', 'License Optimization', 'technology-financial-management', 'cost-optimization', 'process-maturity'),
  capability('cloud-cost-management', 'Cloud Cost Management', 'technology-financial-management', 'cost-optimization', 'process-maturity', ['cloud-infrastructure']),
  capability('vendor-cost-review', 'Vendor Cost Review', 'technology-financial-management', 'cost-optimization', 'process-maturity', ['vendor-strategy']),
  capability('cost-allocation', 'Cost Allocation', 'technology-financial-management', 'cost-optimization', 'process-maturity'),
  capability('technology-investment-evaluation', 'Technology Investment Evaluation', 'technology-financial-management', 'cost-optimization', 'process-maturity'),
  capability('total-cost-ownership', 'Total Cost of Ownership', 'technology-financial-management', 'cost-optimization', 'business-capability'),
  capability('financial-forecasting', 'Financial Forecasting', 'technology-financial-management', 'cost-optimization', 'process-maturity'),
  capability('technology-value-measurement', 'Technology Value Measurement', 'technology-financial-management', 'cost-optimization', 'business-capability'),

  capability('application-inventory', 'Application Inventory', 'application-software-management', 'technology-operations', 'process-maturity'),
  capability('application-ownership', 'Application Ownership', 'application-software-management', 'technology-operations', 'process-maturity'),
  capability('application-lifecycle-management', 'Application Lifecycle Management', 'application-software-management', 'technology-operations', 'process-maturity'),
  capability('application-access-management', 'Application Access Management', 'application-software-management', 'identity-access', 'control-status'),
  capability('application-configuration-management', 'Application Configuration Management', 'application-software-management', 'technology-operations', 'process-maturity'),
  capability('application-integration-management', 'Application Integration Management', 'application-software-management', 'technology-operations', 'process-maturity'),
  capability('custom-software-management', 'Custom Software Management', 'application-software-management', 'technology-operations', 'process-maturity'),
  capability('application-security', 'Application Security', 'application-software-management', 'cybersecurity', 'control-status'),
  capability('software-dependency-management', 'Software Dependency Management', 'application-software-management', 'cybersecurity', 'process-maturity'),
  capability('application-supportability', 'Application Supportability', 'application-software-management', 'technology-operations', 'business-capability'),
  capability('shadow-technology-management', 'Shadow Technology Management', 'application-software-management', 'governance-risk', 'process-maturity'),

  capability('ai-tool-inventory', 'AI Tool Inventory', 'ai-governance-enablement', 'ai-readiness', 'process-maturity'),
  capability('approved-ai-tools', 'Approved AI Tools', 'ai-governance-enablement', 'ai-readiness', 'process-maturity'),
  capability('ai-data-governance', 'AI Data Governance', 'ai-governance-enablement', 'ai-readiness', 'process-maturity', ['governance-risk']),
  capability('ai-use-policy', 'AI Use Policy', 'ai-governance-enablement', 'ai-readiness', 'process-maturity'),
  capability('ai-access-management', 'AI Access Management', 'ai-governance-enablement', 'ai-readiness', 'control-status', ['identity-access']),
  capability('ai-vendor-evaluation', 'AI Vendor Evaluation', 'ai-governance-enablement', 'ai-readiness', 'process-maturity', ['vendor-strategy']),
  capability('ai-output-review', 'AI Output Review', 'ai-governance-enablement', 'ai-readiness', 'process-maturity'),
  capability('ai-risk-management', 'AI Risk Management', 'ai-governance-enablement', 'ai-readiness', 'process-maturity', ['governance-risk']),
  capability('ai-opportunity-assessment', 'AI Opportunity Assessment', 'ai-governance-enablement', 'ai-readiness', 'business-capability'),
  capability('ai-use-case-prioritization', 'AI Use-Case Prioritization', 'ai-governance-enablement', 'ai-readiness', 'process-maturity'),
  capability('employee-ai-enablement', 'Employee AI Enablement', 'ai-governance-enablement', 'ai-readiness', 'process-maturity'),
  capability('ai-solution-monitoring', 'AI Solution Monitoring', 'ai-governance-enablement', 'ai-readiness', 'process-maturity'),
];
