import type { CapabilityQuestion } from '../../types.ts';

export const businessServiceCriticalityQuestions: CapabilityQuestion[] = [
  {
    id: 'business-critical-services',
    capabilityId: 'business-service-criticality',
    prompt: 'Can business leaders identify and rank the services that must continue during a major disruption?',
    description: 'Consider revenue-producing work, customer commitments, safety, legal obligations, and essential internal operations.',
    responseType: 'single-choice',
    evidenceRequirements: [{ id: 'critical-service-register', label: 'Critical-service register', description: 'A reviewed list of critical business services with owners and relative priority.', preferredSource: 'documentation' }],
    options: [
      { id: 'informal', label: 'Known informally by a few leaders', maturityScore: 2 },
      { id: 'partial', label: 'Documented for some major services', maturityScore: 3 },
      { id: 'reviewed', label: 'Documented and reviewed with business owners', maturityScore: 4 },
      { id: 'tested', label: 'Reviewed, prioritized, and used in continuity exercises', maturityScore: 5 },
    ],
    allowUnknown: true,
    unknownBehavior: { type: 'visibility-finding', findingId: 'critical-services-unidentified' },
    importance: 5,
    severity: 'high',
    foundational: true,
    standardMappingIds: ['business-criticality-iso22301', 'business-criticality-nist'],
  },
  {
    id: 'business-service-dependencies',
    capabilityId: 'business-service-criticality',
    prompt: 'Are the key technology, vendor, people, and data dependencies of critical services documented?',
    responseType: 'single-choice',
    evidenceRequirements: [{ id: 'service-dependency-map', label: 'Service dependency map', description: 'A current record connecting critical services to their major applications, vendors, data, infrastructure, and owners.', preferredSource: 'documentation' }],
    options: [
      { id: 'informal', label: 'Known informally or only by technical staff', maturityScore: 2 },
      { id: 'partial', label: 'Documented for the most important services', maturityScore: 3 },
      { id: 'reviewed', label: 'Documented and reviewed after significant changes', maturityScore: 4 },
      { id: 'tested', label: 'Used in recovery planning and exercises', maturityScore: 5 },
    ],
    allowUnknown: true,
    unknownBehavior: { type: 'visibility-finding', findingId: 'critical-service-dependencies-unclear' },
    importance: 4,
    severity: 'high',
    foundational: true,
    standardMappingIds: ['business-criticality-iso22301', 'business-criticality-itil'],
  },
  {
    id: 'business-recovery-priorities',
    capabilityId: 'business-service-criticality',
    prompt: 'Are the most critical business services assigned clear priority tiers based on business impact?',
    responseType: 'single-choice',
    evidenceRequirements: [{ id: 'recovery-priority-record', label: 'Recovery priority record', description: 'Business-approved recovery priorities or time objectives for critical services.', preferredSource: 'documentation' }],
    options: [
      { id: 'informal', label: 'Discussed informally when an outage occurs', maturityScore: 2 },
      { id: 'partial', label: 'Priority tiers exist for some critical services', maturityScore: 3 },
      { id: 'reviewed', label: 'Priority tiers are documented and approved by business owners', maturityScore: 4 },
      { id: 'tested', label: 'Priority tiers are approved and used in continuity exercises', maturityScore: 5 },
    ],
    allowUnknown: true,
    unknownBehavior: { type: 'visibility-finding', findingId: 'business-recovery-priorities-undefined' },
    importance: 4,
    severity: 'high',
    foundational: true,
    standardMappingIds: ['business-criticality-iso22301', 'business-criticality-nist'],
  },
];
